/* 
 * File:   MCAL_INTERRUPT_CONFIG.h
 * Author: Alaa
 *
 * Created on April 20, 2024, 2:50 PM
 */

#ifndef MCAL_INTERRUPT_CONFIG_H
#define	MCAL_INTERRUPT_CONFIG_H

#include "pic18f4620.h"
#include "MCAL_INTERRUPT_GEN_CFG.h"
#include "../GPIO/HAL_GPIO.h"

#define INTERRUPT_OCCURED  0x01
#define INTERRUPT_ENABLED  0x01
#define INTERRUPT_DISABLED 0x00



#ifdef PRIORITY_FEATURE_ENABLED


typedef enum{
    PRIORITY_LOW,
    PRIORITY_HIGH,
}Priority_t;




#define INTERRUPT_PRIORITY_FEATURE_ENABLE    (RCONbits.IPEN = 1)
#define INTERRUPT_PRIORITY_FEATURE_DISABLE   (RCONbits.IPEN = 0)

#define INTERRUPT_PRIORITY_HIGH_ENABLE       (INTCONbits.GIEH = 1)
#define INTERRUPT_PRIORITY_HIGH_DISABLE      (INTCONbits.GIEH = 0)

#define INTERRUPT_PRIORITY_LOW_ENABLE        (INTCONbits.GIEL = 1)
#define INTERRUPT_PRIORITY_LOW_DISABLE       (INTCONbits.GIEL = 0)

#else

#define INTERRUPT_GENERAL_FEATURE_ENABLE     (INTCONbits.GIE = 1)
#define INTERRUPT_GENERAL_FEATURE_DISABLE    (INTCONbits.GIE = 0)

#define INTERRUPT_PERIPHERAL_FEATURE_ENABLE  (INTCONbits.PEIE = 1)
#define INTERRUPT_PERIPHERAL_FEATURE_DISABLE (INTCONbits.PEIE = 0)

#endif

#endif	/* MCAL_INTERRUPT_CONFIG_H */