/* 
 * File:   MCAL_INTERRUPT_GEN_CFG.h
 * Author: Alaa
 *
 * Created on April 21, 2024, 2:56 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

//#define PRIORITY_FEATURE_ENABLED

#define INTx_FEATURE_ENABLE

#define RBx_FEATURE_ENABLE

#define ADC_INTERRUPT_FEATURE_ENABLE

#define TIMER0_INTERRUPT_FEATURE_ENABLE

#define TIMER1_INTERRUPT_FEATURE_ENABLE

#define TIMER2_INTERRUPT_FEATURE_ENABLE

#define TIMER3_INTERRUPT_FEATURE_ENABLE


#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

